ST_CLIENT_ID: "ST CLIENT ID"
ST_CLIENT_SECRET: "ST CLIENT SECRET"
UBI_CLIENT_ID: "UBI CLIENT ID"
UBI_CLIENT_SECRET: "UBI CLIENT SECRET"
WINK_CLIENT_ID: "WINK CLIENT ID"
WINK_CLIENT_SECRET: "WINK CLIENT SECRET"
THINGLAYER_DATABASE_PASSWORD: "DB PASS"
SECRET_KEY_BASE: "SECRET KEY BASE(run rake secret to get one)"
